spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: http://localhost:8080   # Load balance requests to product service
          predicates:
            - Path=/product/**
            - StripPrefix=1
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE   # Load balance requests to order service
          predicates:
            - Path=/order/**
            - StripPrefix=1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE  # Load balance requests to payment service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1    # Strip the prefix "/payment" from the incoming request

    eureka:
      instance:
        hostname: localhost  # This sets the hostname as 'localhost' when registering with Eureka
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # Point to the Eureka server
        fetch-registry: true
        register-with-eureka: true  # Ensure this service registers itself with Eureka



logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

server:
  port: 9090  # Cloud Gateway running on port 8080
