
spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://microtest-user.cbcoqks0yis3.us-east-1.rds.amazonaws.com/postgres
    username: olawale
    password: Olawale22
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: product
    hibernate:
      ddl-auto: validate
    show-sql: true



    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server
        register-with-eureka: true  # This client should register itself with Eureka
        fetch-registry: true

